{
 "title": "Plebbit Uptime Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ipfs_gateway_url",
    "label": "ipfs_gateway_url",
    "query": {
     "query": "label_values(plebbit_uptime_monitor_ipfs_gateway_comment_fetch_count, ipfs_gateway_url)"
    }
   },
   {
    "name": "subplebbit_address",
    "label": "subplebbit_address",
    "query": {
     "query": "label_values(plebbit_uptime_monitor_subplebbit_update_fetch_count, subplebbit_address)"
    }
   },
   {
    "name": "http_router_url",
    "label": "http_router_url",
    "query": {
     "query": "label_values(plebbit_uptime_monitor_http_router_get_providers_fetch_count, http_router_url)"
    }
   },
   {
    "name": "chain_provider_url",
    "label": "chain_provider_url",
    "query": {
     "query": "label_values(plebbit_uptime_monitor_chain_provider_resolve_address_count, chain_provider_url)"
    }
   },
   {
    "name": "nft_name",
    "label": "nft_name",
    "query": {
     "query": "label_values(plebbit_uptime_monitor_nft_ipfs_gateway_fetch_count, nft_name)"
    }
   },
   {
    "name": "pubsub_provider_url",
    "label": "pubsub_provider_url",
    "query": {
     "query": "label_values(plebbit_uptime_monitor_pubsub_provider_publish_count, pubsub_provider_url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Plebbit Uptime Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    { "expr": "plebbit_uptime_monitor_up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "IPFS Gateway Comment Fetch Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "plebbit_uptime_monitor_ipfs_gateway_comment_fetch_count",
     "legendFormat": "{{ipfs_gateway_url}}"
    }
   ]
  },
  {
   "title": "Plebbit Previewer Fetch Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "plebbit_uptime_monitor_plebbit_previewer_comment_preview_fetch_count",
     "legendFormat": "{{plebbit_previewer_url}}"
    }
   ]
  },
  {
   "title": "HTTP Router Get Providers Fetch Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "plebbit_uptime_monitor_http_router_get_providers_fetch_count",
     "legendFormat": "{{http_router_url}}"
    }
   ]
  },
  {
   "title": "Webpage Fetch Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "plebbit_uptime_monitor_webpage_webpage_fetch_count",
     "legendFormat": "{{webpage_url}}"
    }
   ]
  },
  {
   "title": "Chain Provider Resolve Address Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "plebbit_uptime_monitor_chain_provider_resolve_address_count",
     "legendFormat": "{{chain_provider_url}}"
    }
   ]
  },
  {
   "title": "IPFS Gateways Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPFS Gateway Comment Fetch Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_ipfs_gateway_comment_fetch_success_count or (plebbit_uptime_monitor_ipfs_gateway_comment_fetch_count * 0)) / plebbit_uptime_monitor_ipfs_gateway_comment_fetch_count",
       "legendFormat": "{{ipfs_gateway_url}}"
      }
     ]
    },
    {
     "title": "IPFS Gateway Comment Fetch Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_duration_seconds or plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_success * 0) * plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_success",
       "legendFormat": "{{ipfs_gateway_url}}"
      }
     ]
    },
    {
     "title": "IPFS Gateway Comment Fetch Attempts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_attempt_count or plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_success * 0) * plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_success",
       "legendFormat": "{{ipfs_gateway_url}}"
      }
     ]
    },
    {
     "title": "IPFS Gateway Comment Fetch Duration Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "seconds/m" } },
     "targets": [
      {
       "expr": "rate(plebbit_uptime_monitor_ipfs_gateway_comment_fetch_duration_seconds_sum[30m]) * 60",
       "legendFormat": "{{ipfs_gateway_url}}"
      }
     ]
    },
    {
     "title": "IPFS Gateway Comment Fetch Attempts Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "attempts/m" } },
     "targets": [
      {
       "expr": "rate(plebbit_uptime_monitor_ipfs_gateway_comment_fetch_attempt_count[30m]) * 60",
       "legendFormat": "{{ipfs_gateway_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPFS Gateways",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPFS Gateway Comment Fetch Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 79 },
     "repeat": "ipfs_gateway_url",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_duration_seconds{ipfs_gateway_url=~\"$ipfs_gateway_url\"} or plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_success{ipfs_gateway_url=~\"$ipfs_gateway_url\"} * 0) * plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_success{ipfs_gateway_url=~\"$ipfs_gateway_url\"}",
       "legendFormat": "{{ipfs_gateway_url}}"
      }
     ]
    },
    {
     "title": "IPFS Gateway Comment Fetch Attempts",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 9, "y": 79 },
     "repeat": "ipfs_gateway_url",
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_attempt_count{ipfs_gateway_url=~\"$ipfs_gateway_url\"} or plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_success{ipfs_gateway_url=~\"$ipfs_gateway_url\"} * 0) * plebbit_uptime_monitor_ipfs_gateway_last_comment_fetch_success{ipfs_gateway_url=~\"$ipfs_gateway_url\"}",
       "legendFormat": "{{ipfs_gateway_url}}"
      }
     ]
    },
    {
     "title": "Subplebbit IPNS Fetch Success",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 79 },
     "repeat": "ipfs_gateway_url",
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_ipfs_gateway_last_subplebbit_ipns_fetch_success{ipfs_gateway_url=~\"$ipfs_gateway_url\"}",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit IPNS Fetch Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 79 },
     "repeat": "ipfs_gateway_url",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(plebbit_uptime_monitor_ipfs_gateway_last_subplebbit_ipns_fetch_success{ipfs_gateway_url=~\"$ipfs_gateway_url\"}) / count(plebbit_uptime_monitor_ipfs_gateway_last_subplebbit_ipns_fetch_success{ipfs_gateway_url=~\"$ipfs_gateway_url\"})",
       "legendFormat": "Success"
      }
     ]
    }
   ]
  },
  {
   "title": "IPFS Gateways Subplebbit IPNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subplebbit",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 64 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_last_subplebbit_update_fetch_seconds_since_updated_at{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0) * plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit Time Since Last Updated",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 64 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_ipfs_gateway_last_subplebbit_ipns_fetch_seconds_since_updated_at{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "{{ipfs_gateway_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pubsub Providers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pubsub Provider Publish Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 65 },
     "repeat": "pubsub_provider_url",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_pubsub_provider_last_publish_duration_seconds{pubsub_provider_url=~\"$pubsub_provider_url\"} or plebbit_uptime_monitor_pubsub_provider_last_publish_success{pubsub_provider_url=~\"$pubsub_provider_url\"} * 0) * plebbit_uptime_monitor_pubsub_provider_last_publish_success{pubsub_provider_url=~\"$pubsub_provider_url\"}",
       "legendFormat": "{{pubsub_provider_url}}"
      }
     ]
    },
    {
     "title": "Pubsub Provider Subscribe Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 65 },
     "repeat": "pubsub_provider_url",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_pubsub_provider_last_subscribe_duration_seconds{pubsub_provider_url=~\"$pubsub_provider_url\"} or plebbit_uptime_monitor_pubsub_provider_last_subscribe_success{pubsub_provider_url=~\"$pubsub_provider_url\"} * 0) * plebbit_uptime_monitor_pubsub_provider_last_subscribe_success{pubsub_provider_url=~\"$pubsub_provider_url\"}",
       "legendFormat": "{{pubsub_provider_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subplebbits Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Popular Subplebbits",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_stats_all_active_user_count",
       "legendFormat": "{{subplebbit_address}}"
      },
      {
       "expr": "plebbit_uptime_monitor_subplebbit_stats_all_post_count",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Plebbit Unique Addresses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "addresses" } },
     "targets": [
      {
       "expr": "sum(plebbit_uptime_monitor_subplebbit_stats_all_active_user_count)",
       "legendFormat": "users"
      }
     ]
    },
    {
     "title": "Plebbit Posts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "posts" } },
     "targets": [
      {
       "expr": "sum(plebbit_uptime_monitor_subplebbit_stats_all_post_count)",
       "legendFormat": "posts"
      }
     ]
    },
    {
     "title": "Subplebbit Update Fetch Success",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_last_subplebbit_update_fetch_success",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit Time Since Last Updated",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_last_subplebbit_update_fetch_seconds_since_updated_at or plebbit_uptime_monitor_last_subplebbit_update_fetch_success * 0) * plebbit_uptime_monitor_last_subplebbit_update_fetch_success",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit Time Since Last Updated",
     "type": "stat",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_last_subplebbit_update_fetch_seconds_since_updated_at or plebbit_uptime_monitor_last_subplebbit_update_fetch_success * 0) * plebbit_uptime_monitor_last_subplebbit_update_fetch_success",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit Time Since Last Pubsub Message",
     "type": "stat",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_pubsub_seconds_since_last_subplebbit_pubsub_message or plebbit_uptime_monitor_last_subplebbit_update_fetch_success * 0",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit IPNS Peers",
     "type": "stat",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "peers" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_last_subplebbit_ipns_http_routers_peer_count or plebbit_uptime_monitor_last_subplebbit_update_fetch_success * 0",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbits Online",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_last_subplebbit_update_fetch_seconds_since_updated_at < 7200 and plebbit_uptime_monitor_last_subplebbit_update_fetch_success != 0 ",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbits Offline",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_last_subplebbit_update_fetch_seconds_since_updated_at >= 7200 or plebbit_uptime_monitor_last_subplebbit_update_fetch_success == 0 ",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subplebbits Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subplebbit",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_last_subplebbit_update_fetch_seconds_since_updated_at{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0) * plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Time Since Updated",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 3, "y": 27 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_last_subplebbit_update_fetch_seconds_since_updated_at{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0) * plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit Time Since Last Updated",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 17, "x": 7, "y": 27 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_last_subplebbit_update_fetch_seconds_since_updated_at{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0) * plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subplebbits Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subplebbit",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 28 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_last_subplebbit_update_fetch_seconds_since_updated_at{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0) * plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit Users",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 3, "y": 28 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "users" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_stats_all_active_user_count{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit Posts",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 10, "y": 28 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "posts" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_stats_all_post_count{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit Replies",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 28 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "replies" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_stats_all_reply_count{subplebbit_address=~\"$subplebbit_address\"} ",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subplebbits Pubsub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subplebbit",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_pubsub_seconds_since_last_subplebbit_pubsub_message{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Updated",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 3, "y": 21 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_last_subplebbit_update_fetch_seconds_since_updated_at{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0) * plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Last Pubsub Message",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 21 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_pubsub_seconds_since_last_subplebbit_pubsub_message{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Time Since Last Pubsub Message",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 8, "y": 21 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_pubsub_seconds_since_last_subplebbit_pubsub_message{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Pubsub Message Count",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 14, "y": 21 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_pubsub_message_count{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Pubsub Peers",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 21 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "peers" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_last_subplebbit_pubsub_pubsub_peer_count{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_pubsub_pubsub_peers_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "HTTP Routers Peers",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 21 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "peers" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_last_subplebbit_pubsub_http_routers_peer_count{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_pubsub_http_routers_peers_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subplebbits Pubsub Publish",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subplebbit",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 30 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_pubsub_seconds_since_last_subplebbit_pubsub_message{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_last_subplebbit_update_fetch_success{subplebbit_address=~\"$subplebbit_address\"} * 0",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Time Since Last Pubsub Message",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 3, "y": 30 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_pubsub_seconds_since_last_subplebbit_pubsub_message{subplebbit_address=~\"$subplebbit_address\"} ",
       "legendFormat": "time since last pubsub message"
      },
      {
       "expr": "plebbit_uptime_monitor_subplebbit_pubsub_last_publish_duration_seconds{subplebbit_address=~\"$subplebbit_address\"} * plebbit_uptime_monitor_subplebbit_pubsub_last_publish_success{subplebbit_address=~\"$subplebbit_address\"} or plebbit_uptime_monitor_subplebbit_pubsub_last_publish_success{subplebbit_address=~\"$subplebbit_address\"} * 0",
       "legendFormat": "last publish duration"
      }
     ]
    },
    {
     "title": "Publish Success",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 30 },
     "repeat": "subplebbit_address",
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_subplebbit_pubsub_last_publish_success{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "success"
      },
      {
       "expr": "plebbit_uptime_monitor_subplebbit_pubsub_last_publish_error_count{subplebbit_address=~\"$subplebbit_address\"}",
       "legendFormat": "error count"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Routers Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Router Get Providers Fetch Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_http_router_get_providers_fetch_success_count or (plebbit_uptime_monitor_http_router_get_providers_fetch_count * 0)) / plebbit_uptime_monitor_http_router_get_providers_fetch_count",
       "legendFormat": "{{http_router_url}}"
      }
     ]
    },
    {
     "title": "HTTP Routers Get Providers Fetch Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_http_router_last_get_providers_fetch_duration_seconds or plebbit_uptime_monitor_http_router_last_get_providers_fetch_success * 0) * plebbit_uptime_monitor_http_router_last_get_providers_fetch_success",
       "legendFormat": "GET {{http_router_url}}"
      },
      {
       "expr": "(plebbit_uptime_monitor_http_router_last_post_providers_fetch_duration_seconds or plebbit_uptime_monitor_http_router_last_get_providers_fetch_success * 0) * plebbit_uptime_monitor_http_router_last_get_providers_fetch_success",
       "legendFormat": "POST {{http_router_url}}"
      }
     ]
    },
    {
     "title": "HTTP Routers Get Providers Fetch Duration Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "fieldConfig": { "defaults": { "unit": "seconds/m" } },
     "targets": [
      {
       "expr": "rate(plebbit_uptime_monitor_http_router_get_providers_fetch_duration_seconds_sum[30m]) * 60",
       "legendFormat": "{{http_router_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Routers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Router Get Providers Fetch Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 136 },
     "repeat": "http_router_url",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_http_router_last_get_providers_fetch_duration_seconds{http_router_url=~\"$http_router_url\"} or plebbit_uptime_monitor_http_router_last_get_providers_fetch_success{http_router_url=~\"$http_router_url\"} * 0) * plebbit_uptime_monitor_http_router_last_get_providers_fetch_success{http_router_url=~\"$http_router_url\"}",
       "legendFormat": "GET {{http_router_url}}"
      },
      {
       "expr": "(plebbit_uptime_monitor_http_router_last_post_providers_fetch_duration_seconds{http_router_url=~\"$http_router_url\"} or plebbit_uptime_monitor_http_router_last_get_providers_fetch_success{http_router_url=~\"$http_router_url\"} * 0) * plebbit_uptime_monitor_http_router_last_get_providers_fetch_success{http_router_url=~\"$http_router_url\"}",
       "legendFormat": "POST {{http_router_url}}"
      }
     ]
    },
    {
     "title": "Subplebbit IPNS Provider Count",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 136 },
     "repeat": "http_router_url",
     "fieldConfig": { "defaults": { "unit": "providers" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_http_router_last_subplebbit_ipns_get_providers_fetch_provider_count{http_router_url=~\"$http_router_url\"} or (plebbit_uptime_monitor_http_router_last_subplebbit_ipns_get_providers_fetch_success{http_router_url=~\"$http_router_url\"} * 0)",
       "legendFormat": "{{subplebbit_address}}"
      }
     ]
    },
    {
     "title": "Subplebbit IPNS Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 136 },
     "repeat": "http_router_url",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "count(plebbit_uptime_monitor_http_router_last_subplebbit_ipns_get_providers_fetch_provider_count{http_router_url=~\"$http_router_url\"} > 0) or vector(0)\n/\ncount(plebbit_uptime_monitor_http_router_last_subplebbit_ipns_get_providers_fetch_success{http_router_url=~\"$http_router_url\"})\n",
       "legendFormat": "Success"
      }
     ]
    }
   ]
  },
  {
   "title": "Chain Providers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chain Provider Resolve Address Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "repeat": "chain_provider_url",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_chain_provider_last_resolve_address_duration_seconds{chain_provider_url=~\"$chain_provider_url\"} or plebbit_uptime_monitor_chain_provider_last_resolve_address_success{chain_provider_url=~\"$chain_provider_url\"} * 0) * plebbit_uptime_monitor_chain_provider_last_resolve_address_success{chain_provider_url=~\"$chain_provider_url\"}",
       "legendFormat": "{{chain_provider_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Plebbit Seeders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Plebbit Seeder Subplebbit Fetch Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_plebbit_seeder_last_subplebbit_update_cid_fetch_duration_seconds or plebbit_uptime_monitor_plebbit_seeder_last_subplebbit_update_cid_fetch_success * 0) * plebbit_uptime_monitor_plebbit_seeder_last_subplebbit_update_cid_fetch_success",
       "legendFormat": "{{plebbit_seeder_peer_id}}"
      }
     ]
    },
    {
     "title": "Plebbit Seeders Offline",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
     "targets": [
      {
       "expr": "timestamp(plebbit_uptime_monitor_plebbit_seeder_last_subplebbit_update_cid_fetch_success == 1) * 1000",
       "legendFormat": "{{plebbit_seeder_peer_id}}"
      },
      {
       "expr": "plebbit_uptime_monitor_plebbit_seeder_last_subplebbit_update_cid_fetch_success",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Plebbit Previewers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Plebbit Previewer Comment Preview Fetch Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_plebbit_previewer_last_comment_preview_fetch_duration_seconds or plebbit_uptime_monitor_plebbit_previewer_last_comment_preview_fetch_success * 0) * plebbit_uptime_monitor_plebbit_previewer_last_comment_preview_fetch_success",
       "legendFormat": "{{plebbit_previewer_url}}"
      }
     ]
    },
    {
     "title": "Plebbit Previewers Offline",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "targets": [
      {
       "expr": "timestamp(plebbit_uptime_monitor_plebbit_previewer_last_comment_preview_fetch_success == 1) * 1000",
       "legendFormat": "{{plebbit_previewer_url}}"
      },
      {
       "expr": "plebbit_uptime_monitor_plebbit_previewer_last_comment_preview_fetch_success",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Webpages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Webpage Fetch Duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(plebbit_uptime_monitor_webpage_last_webpage_fetch_duration_seconds or plebbit_uptime_monitor_webpage_last_webpage_fetch_success * 0) * plebbit_uptime_monitor_webpage_last_webpage_fetch_success",
       "legendFormat": "{{webpage_url}}"
      }
     ]
    },
    {
     "title": "Webpages Offline",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
     "targets": [
      {
       "expr": "timestamp(plebbit_uptime_monitor_webpage_last_webpage_fetch_success == 1) * 1000",
       "legendFormat": "{{webpage_url}}"
      },
      {
       "expr": "plebbit_uptime_monitor_webpage_last_webpage_fetch_success",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "NFTs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFT IPFS Gateway Fetch Success",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 108 },
     "repeat": "nft_name",
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "plebbit_uptime_monitor_nft_last_ipfs_gateway_fetch_success{nft_name=~\"$nft_name\"}",
       "legendFormat": "{{nft_name}} {{ipfs_gateway_url}}"
      }
     ]
    }
   ]
  }
 ]
}